kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: nifcloud-nas-csi-controller
  namespace: nifcloud-nas-csi-driver
spec:
  serviceName: "nifcloud-nas-csi-driver"
  replicas: 1
  selector:
    matchLabels:
      app: nifcloud-nas-csi-driver
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nifcloud-nas-csi-driver
    spec:
      serviceAccount: nifcloud-nas-csi-controller-sa
      hostNetwork: true
      containers:
        - name: csi-external-provisioner
          imagePullPolicy: Always
          image: k8s.gcr.io/sig-storage/csi-provisioner:v2.0.2
          args:
            - "--timeout=30m"
            - "--v=4"
            - "--csi-address=/csi/csi.sock"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-snapshotter
          image: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.0
          args:
            - "--timeout=30m"
            - "--v=4"
            - "--csi-address=/csi/csi.sock"
            #- --leader-election=true
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: nifcloud-nas-driver
          securityContext:
            privileged: true
          imagePullPolicy: Always
          image: [image]:[tag]
          args:
            - "--v=4"
            - "--endpoint=unix:/csi/csi.sock"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--controller=true"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: cloud-credential
                  key: accesskey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cloud-credential
                  key: secretkey
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: host-tmp
              mountPath: /tmp
              mountPropagation: "Bidirectional"
      volumes:
        - name: host-tmp
          hostPath:
            path: /tmp
            type: Directory
        - name: socket-dir
          emptyDir: {}
