apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: nas.csi.storage.nifcloud.com
spec:
  attachRequired: true
  podInfoOnMount: true
  volumeLifecycleModes: # added in Kubernetes 1.16
  - Persistent
  - Ephemeral
