apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: nas.csi.storage.nifcloud.com
spec:
  # skip attach and detach
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes: # added in Kubernetes 1.16
  - Persistent
  - Ephemeral
