apiVersion: v1
kind: Namespace
metadata:
  name: nifcloud-nas-csi-driver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nifcloud-nas-csi-node-sa
  namespace: nifcloud-nas-csi-driver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nifcloud-nas-csi-controller-sa
  namespace: nifcloud-nas-csi-driver
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifcloud-nas-csi-controller
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["csinodes"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifcloud-nas-csi-controller-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: nifcloud-nas-csi-controller-sa
    namespace: nifcloud-nas-csi-driver
roleRef:
  kind: ClusterRole
  name: nifcloud-nas-csi-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nifcloud-nas-csi-node
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "update"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["storage.k8s.io"]
  resources: ["csinodes"]
  verbs: ["get", "list", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifcloud-nas-csi-node-binding
subjects:
  - kind: ServiceAccount
    name: nifcloud-nas-csi-node-sa
    namespace: nifcloud-nas-csi-driver
roleRef:
  kind: ClusterRole
  name: nifcloud-nas-csi-node
  apiGroup: rbac.authorization.k8s.io
