apiVersion: v1
kind: Namespace
metadata:
  name: nifcloud-nas-csi-driver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nifcloud-nas-csi-node-sa
  namespace: nifcloud-nas-csi-driver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nifcloud-nas-csi-controller-sa
  namespace: nifcloud-nas-csi-driver
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifcloud-nas-csi-controller-provisioner-binding
subjects:
  - kind: ServiceAccount
    name: nifcloud-nas-csi-controller-sa
    namespace: nifcloud-nas-csi-driver
roleRef:
  kind: ClusterRole
  name: system:csi-external-provisioner
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifcloud-nas-csi-controller-attacher-binding
subjects:
  - kind: ServiceAccount
    name: nifcloud-nas-csi-controller-sa
    namespace: nifcloud-nas-csi-driver
roleRef:
  kind: ClusterRole
  name: system:csi-external-attacher
  apiGroup: rbac.authorization.k8s.io
