apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: testclaim-snap
  namespace: default
spec:
  volumeSnapshotClassName: csi-nifcloud-rstc
  source:
    persistentVolumeClaimName: testclaim