apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-nifcloud-nas-shrd
provisioner: nas.csi.storage.nifcloud.com
parameters:
  zone: east-11
  instanceType: "0"
  securityGroup: c01nasfw
  networkId: net-0123abcd
  reservedIpv4Cidr: 192.168.20.0/26
  capacityParInstanceGiB: "500"
  shared: "true"
