name: Go

on:
  push:
    paths-ignore:
    - '**.yml'
    - '**.yaml'
    - '**.md'
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./pkg/cloud ./pkg/driver --cover
