name: golangci-lint
on:
  push:
    paths-ignore:
    - '**.yml'
    - '**.yaml'
    - '**.md'
  pull_request:
    branches: [ master ]
jobs:
  ci-lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.40.1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run golanci-lint
        run: |
          go mod vendor
          golangci-lint run -v
